fix: Change preNavigationHooks to array format
Error: ArgumentError: Expected property preNavigationHooks to be of type array
but received type Function in object PlaywrightCrawlerOptions

Solution: Wrap the function in an array as required by Crawlee API

preNavigationHooks: [async ({ page, request }) => { ... }]